---
title: "methods_standardReview"
format: html
editor: 
  markdown: 
    wrap: 72
---

Analysis used Raven 1.6.4

Need to figure out:

How to mark start/end

How to mark noisy areas (end/restart)

What selections to put in table

What size/view for spectrograms

how to view/review data to review up to 2.5kHz (and settings for each)

### Open Files

-   Page size 180 s

-   Page increment 90 %

-   Step 10%

### Spectrogram View

-   Remove Waveform

-   View 2 channels

Identify Start and End of recordings

-   For each START (either at the beginning, or after a bout of noise
    where I selected to END), create a box where the START of the box
    lies on the noise. Annotate start_end as 'start' and NA for others.

-   For each END (either at the end of a good bout of recording or the
    end of the entire recording), create a box where the end of the box
    lies on the end of the good recording (note: the end of a good
    recording can also identify the start of bad noise). If this is the
    end of a recording, then label the other annotations as "NA". If
    this is the end of a good recording but start of noise, label the
    detection as "noise" and the quality as NA.

## Methods

Audio files were decimated using Triton vXXX (Matlab, cite) at 10x and
and 100x, giving 4800 Hz and 480 Hz decimated sample rate, respectively.
Data were reviewed at both of these decimation rates for DIFAR buoys,
and an additional review at full bandwidth (48 kHz) was conducted for
omni directional recordings from sonobuoy types 57.

### Mid-Frequency Review

Recordings decimated to 4800 Hz were reviewed using RavenPro Software
(v1.6.4). Page size = 60 seconds, 90% increment, 10% step increment.
View only spectrogram (not waveform), 2 rows with 512 FFT with 200 Hz to
2400 Hz in window.
